language: node_js
node_js:
- '8'
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _book
  on:
    branch: master
env:
  global:
  - secure: C75VqDpclTvcP9/2jBM9rHuoElNR8HZr8e/4CstqrLBZfoXFJ2Bt1UgiFgfvhJsGVImw8EEA+MSuJzU5o3J3ljYB1LIh3hLwFUubOx5xVSXk1bGUGd7UcJlz9OZ8939gQDUlpOmfFDt8+ohwOgriydGEexP0UZdZww4w9y2Pj7T2LGrvceoVCJAjChWEFb1atmUnZa7v0Ylk6SvTLSp74lHjGxz5jSxdG0Gte/Ng4IUa3O+NVmfnNsncSNlqxzPrELZWc9MI3daMJAzY5OvXyjh19rNTfrXSCIbU9CSo82hGG9SxLKO3QVXBgA55xzaCLpq/3SmZ8fpvc17mLBMjUwlGbhgkbwvZiNCiiS2SrZpsa6QFnqy++J4jMtWSZR7Z0BYSv37K2q+wtNJSwTEmHFfaQ3nGFc+BAgINsiC7zbcDsollB5mZqpe0zVRpYX1twONjIf59f8NlZMvA+mZIZ+mvrjyNvDGXEwbv/UM0riqoFYVA0Lagb7Bub902JQrsNk47s5JeBUhum3r2bmwZz/Eteur/ZaMQ/bAWJwbkYVqLSNhuJxj7nSnrDbJyKp28L0Y2DcCXsIwbGsHxVcRNUiuNLlpqhg5DiJtrqkfOdDV8ewNWo1cy0jeXC0+vQiR6UTWFMFaOJudMS9YW+bc+JHBn7u8silcGrsrWEcF5Gfk=
